# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c45624e6b95f4d8fe4fdfdbe4c958b31"
name = "pulpoar-try-on"
handle = "pulpoar-try-on"
application_url = "https://pulpoar.onrender.com/"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_script_tags,write_products,write_own_subscription,write_own_subscription_billing"

[auth]
redirect_urls = [ "https://pulpoar.onrender.com/api/auth" ]

[pos]
embedded = false
