# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f234cdf6be463ed64055dd49b74769b1"
name = "pulpoar-try-on"
handle = "pulpoar-try-on"
application_url = "https://exactly-market-avoiding-dns.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://exactly-market-avoiding-dns.trycloudflare.com/auth/callback",
  "https://exactly-market-avoiding-dns.trycloudflare.com/auth/shopify/callback",
  "https://exactly-market-avoiding-dns.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
